name: deploy

on:
  push:
    branches: [main]

jobs:
  deploycode:
    runs-on: ubuntu-latest

    steps:
      - name: practice
        run: echo "code deployed successfully!"
      - name: Post deployment comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request ? context.payload.pull_request.number : null,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "ðŸš€ Code deployed successfully!"
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}